#! /bin/sh

sxhkd &
xsetroot -cursor_name left_ptr &

[wm config]
#bspc config border_radius        25
bspc config border_width          2
bspc config window_gap            7

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer false
bspc config single_monocle        true

#source the colors located within a shell script from your cache (you don't need to touch this).
. "${HOME}/.cache/wal/colors.sh"

#Set the border colors for your windows for focused, active and inactive ones.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color1"
bspc config presel_feedback_color "$color1"

bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc monitor -d 1 2 3 4 5

[rules]
bspc rule -a firefox desktop='^1' follow=on
bspc rule -a atom desktop='^2' follow=on
#bspc rule -a qBittorrent desktop='^2' follow=on
#bspc rule -a gnome-terminal desktop='^3' follow=on
#bspc rule -a Pcmanfm desktop='^4' follow=on
#bspc rule -a mpv state=floating desktop='^6' follow=on
#bspc rule -a Gimp-2.10 desktop='^7' follow=on focus=on
#bspc rule -a feh state=floating follow=on
bspc rule -a lxappearance state=floating follow=on
#bspc rule -a Screenkey manage=off

#startup
#$HOME/.config/polybar/launch.sh

polybar Principal &

#feh --bg-fill ~/Imágenes/prueba.jpg
wal -R

;para randomizar los wallpapers:
;feh --bg-center $(find ~/Imágenes/Wallpapers -type f | shuf -n 1)
mpd &	
dunst &
picom &

